import { createMockAdapter } from "./base";
import type { RawListing } from "./types";

const IMG_TOP_HANDLE = "https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=800";
const IMG_SHOULDER = "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=800";
const IMG_TOTE = "https://images.unsplash.com/photo-1594938298603-c8148c4b4f7a?w=800";
const IMG_CROSSBODY = "https://images.unsplash.com/photo-1622560480605-d83c853bc5c3?w=800";

const listings: RawListing[] = [
  {
    externalId: "trr-001",
    title: "Chanel Boy Bag Medium Navy Lambskin",
    brand: "Chanel",
    model: "Boy Bag",
    style: "Shoulder Bag",
    color: "Navy",
    size: "Medium",
    condition: "Excellent",
    price: 5800,
    originalPrice: 6500,
    imageUrl: IMG_SHOULDER,
    description: "Chanel Boy Bag in Navy Blue Lambskin leather with Silver hardware.",
  },
  {
    externalId: "trr-002",
    title: "Prada Galleria Medium Saffiano Black",
    brand: "Prada",
    model: "Galleria",
    style: "Top Handle",
    color: "Black",
    size: "Medium",
    condition: "Very Good",
    price: 1650,
    imageUrl: IMG_TOP_HANDLE,
    description: "Prada Galleria in Black Saffiano leather. Clean interior.",
  },
  {
    externalId: "trr-003",
    title: "Celine Micro Luggage Caramel",
    brand: "Celine",
    model: "Luggage",
    style: "Top Handle",
    color: "Caramel",
    size: "Micro",
    condition: "Good",
    price: 1200,
    originalPrice: 1600,
    imageUrl: IMG_TOP_HANDLE,
    description: "Celine Micro Luggage in Caramel Smooth Leather.",
  },
  {
    externalId: "trr-004",
    title: "Hermès Birkin 35 Bordeaux Togo",
    brand: "Hermès",
    model: "Birkin",
    style: "Top Handle",
    color: "Bordeaux",
    size: "Birkin 35",
    condition: "Very Good",
    price: 14500,
    imageUrl: IMG_TOP_HANDLE,
    description: "Hermès Birkin 35 in Bordeaux Togo leather with Gold hardware.",
  },
  {
    externalId: "trr-005",
    title: "Chanel Reissue 226 Aged Calfskin Black",
    brand: "Chanel",
    model: "Reissue 226",
    style: "Shoulder Bag",
    color: "Black",
    size: "226",
    condition: "Excellent",
    price: 6400,
    imageUrl: IMG_SHOULDER,
    description: "Chanel Reissue 2.55 226 in Black Aged Calfskin.",
  },
  {
    externalId: "trr-006",
    title: "Louis Vuitton Twist MM Epi Red",
    brand: "Louis Vuitton",
    model: "Twist MM",
    style: "Shoulder Bag",
    color: "Red",
    size: "MM",
    condition: "Pristine",
    price: 4200,
    originalPrice: 4900,
    imageUrl: IMG_SHOULDER,
    description: "Louis Vuitton Twist MM in Red Epi leather.",
  },
  {
    externalId: "trr-007",
    title: "Dior 30 Montaigne Calfskin Beige",
    brand: "Dior",
    model: "30 Montaigne",
    style: "Shoulder Bag",
    color: "Beige",
    size: "Medium",
    condition: "Excellent",
    price: 3400,
    imageUrl: IMG_SHOULDER,
    description: "Dior 30 Montaigne in Beige Box Calfskin.",
  },
  {
    externalId: "trr-008",
    title: "Gucci Jackie 1961 Mini Black",
    brand: "Gucci",
    model: "Jackie 1961",
    style: "Hobo",
    color: "Black",
    size: "Mini",
    condition: "Pristine",
    price: 2400,
    imageUrl: IMG_SHOULDER,
    description: "Gucci Jackie 1961 Mini Hobo in Black Smooth Leather.",
  },
  {
    externalId: "trr-009",
    title: "YSL Sunset Medium Black Croc-Embossed",
    brand: "YSL",
    model: "Sunset",
    style: "Shoulder Bag",
    color: "Black",
    size: "Medium",
    condition: "Very Good",
    price: 1750,
    imageUrl: IMG_SHOULDER,
    description: "Saint Laurent Sunset Medium in Black Croc-Embossed leather.",
  },
  {
    externalId: "trr-010",
    title: "Bottega Veneta The Pouch Small Pink",
    brand: "Bottega",
    model: "The Pouch",
    style: "Clutch",
    color: "Blush",
    size: "Small",
    condition: "Excellent",
    price: 1400,
    imageUrl: IMG_SHOULDER,
    description: "Bottega Veneta The Pouch Small in Blush Pink Nappa.",
  },
  {
    externalId: "trr-011",
    title: "Prada Symbole Saffiano Black",
    brand: "Prada",
    model: "Symbole",
    style: "Crossbody",
    color: "Black",
    size: "Small",
    condition: "Pristine",
    price: 2800,
    imageUrl: IMG_CROSSBODY,
    description: "Prada Symbole in Black Saffiano leather with triangle logo.",
  },
  {
    externalId: "trr-012",
    title: "Loewe Hammock Medium Tan",
    brand: "Loewe",
    model: "Hammock",
    style: "Shoulder Bag",
    color: "Tan",
    size: "Medium",
    condition: "Excellent",
    price: 2600,
    imageUrl: IMG_SHOULDER,
    description: "Loewe Hammock Medium in Tan Classic Calfskin.",
  },
  {
    externalId: "trr-013",
    title: "Fendi Peekaboo Mini Brown Selleria",
    brand: "Fendi",
    model: "Peekaboo",
    style: "Top Handle",
    color: "Brown",
    size: "Mini",
    condition: "Very Good",
    price: 3200,
    imageUrl: IMG_TOP_HANDLE,
    description: "Fendi Peekaboo Mini in Brown Selleria leather.",
  },
  {
    externalId: "trr-014",
    title: "Hermès Evelyne PM Black Clemence",
    brand: "Hermès",
    model: "Evelyne PM",
    style: "Crossbody",
    color: "Black",
    size: "PM",
    condition: "Excellent",
    price: 3800,
    imageUrl: IMG_CROSSBODY,
    description: "Hermès Evelyne PM in Black Clémence leather.",
  },
  {
    externalId: "trr-015",
    title: "Chanel Vintage Diana Black Lambskin",
    brand: "Chanel",
    model: "Diana",
    style: "Shoulder Bag",
    color: "Black",
    size: "Medium",
    condition: "Good",
    price: 4200,
    originalPrice: 4800,
    imageUrl: IMG_SHOULDER,
    description: "Chanel Vintage Diana in Black Lambskin with Gold hardware.",
  },
  {
    externalId: "trr-016",
    title: "Louis Vuitton Petit Noé Epi Black",
    brand: "Louis Vuitton",
    model: "Petit Noé",
    style: "Bucket Bag",
    color: "Black",
    size: "Small",
    condition: "Very Good",
    price: 1150,
    imageUrl: IMG_SHOULDER,
    description: "Louis Vuitton Petit Noé in Black Epi leather.",
  },
  {
    externalId: "trr-017",
    title: "Dior Mini Lady Dior Lambskin Pink",
    brand: "Christian Dior",
    model: "Lady Dior",
    style: "Crossbody",
    color: "Rose",
    size: "Mini",
    condition: "Pristine",
    price: 4800,
    imageUrl: IMG_CROSSBODY,
    description: "Dior Mini Lady Dior in Rose Lambskin Cannage.",
  },
  {
    externalId: "trr-018",
    title: "Goyard Anjou Mini Black Tan",
    brand: "Goyard",
    model: "Anjou Mini",
    style: "Tote",
    color: "Black",
    size: "Mini",
    condition: "Excellent",
    price: 1950,
    imageUrl: IMG_TOTE,
    description: "Goyard Anjou Mini reversible tote in Black/Tan Goyardine canvas.",
  },
  {
    externalId: "trr-019",
    title: "Miu Miu Coffer Bag Brown Leather",
    brand: "Miu Miu",
    model: "Coffer",
    style: "Top Handle",
    color: "Brown",
    size: "Medium",
    condition: "Good",
    price: 850,
    originalPrice: 1100,
    imageUrl: IMG_TOP_HANDLE,
    description: "Miu Miu Coffer Bag in Brown Ruched Leather.",
  },
  {
    externalId: "trr-020",
    title: "Saint Laurent Kate Tassel Medium Black",
    brand: "Saint Laurent",
    model: "Kate",
    style: "Shoulder Bag",
    color: "Black",
    size: "Medium",
    condition: "Pristine",
    price: 1950,
    imageUrl: IMG_SHOULDER,
    description: "Saint Laurent Kate Medium with Tassel in Black Grained Leather.",
  },
];

const adapter = createMockAdapter({
  sourceName: "The RealReal",
  sourceSlug: "therealreal",
  baseUrl: "https://www.therealreal.com",
  listings,
});

export default adapter;
